name: formura
version: '2.3.1'
synopsis: Formura is a simple language to describe stencil computation.
category: Language
author: Takayuki Muranushi, Youhei Ishihara
maintainer: y.ishihara.1993@gmail.com
license: MIT
homepage: https://github.com/formura/formura#readme
git: git://github.com/formura/formura.git
ghc-options:
- -O3
- -Wall
- -fno-warn-unused-do-bind
dependencies:
- base ==4.*
- aeson
- ansi-wl-pprint
- bytestring
- containers
- filepath
- lens
- mtl
- scientific
- text
- trifecta
- yaml
- unordered-containers

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  ghc-options:
  - -fsimpl-tick-factor=326680
  dependencies:
  - array
  - binary-search >=1.0.0.3
  - blaze-markup
  - cases
  - directory
  - filepath
  - gitrev
  - hashable
  - lattices
  - mmorph
  - optparse-applicative
  - parsers
  - process
  - QuickCheck
  - sbv
  - syb
  - temporary
  - tostring
  - transformers
  - vector

executables:
  formura:
    main: formura.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    dependencies:
    - formura
  formura0:
    main: formura0.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    dependencies:
    - formura

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - formura
    - hspec
