length_per_node: [0.1, 0.5, 0.1] # length of each axis per MPI node (Must)
grid_per_node: [10, 50, 10]    # number of grids of each axis per MPI node (Must)
mpi_shape: [1,8,1]          # number of MPI nodes of each axis (Optional)
